- name: SonarCloud Scan
  on: push
  # You may pin to the exact commit or the version.
  # uses: SonarSource/sonarcloud-github-action@32ea6119a4bd977dc6307acb6bbbf277152ede95
  uses: SonarSource/sonarcloud-github-action@v1.5
  with:
    # Additional arguments to the sonarcloud scanner
    args: # optional
    # Set the sonar.projectBaseDir analysis property
    projectBaseDir: # optional, default is .